title: CKD Cat Supplies
description: Not a shop. A collection of tried and true products and resources for CKD kitties and their guardians.
theme: just-the-docs

url: https://ckdcatsupplies.com

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-target-blank

markdown: kramdown

callouts:
  lunasays:
    title: Luna Says
    color: yellow

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
